### ISSUE TITLE
七牛文件详情错误

### ISSUE THREAD

**Issue by MoeGakuen** [HFO4/shudong-share#10]
上传在七牛云储存的文件，详情获取错误。
`object(Qiniu_Error)#8 (4) { ["Err"]=> string(14) "no such bucket" ["Reqid"]=> string(16) "wgYAANnmCTi_VlcU" ["Details"]=> string(0) "" ["Code"]=> int(631) }`

**Comment by MoeGakuen** [comment]
http://xxxxxx/includes/getinfo.php?key=xxxxx

**Comment by HFO4** [comment]
空间不存在，可能是空间名填错，或者空间被删
