### ISSUE TITLE
安装失败！Cannot connect to MySQL,,bad,:Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by Johnhacker** [HFO4/shudong-share#14]
你好，安装后，/admin ，就是这样子Cannot connect to MySQL,,bad,:Access denied for user ''@'localhost' (using password: NO)   

install文件夹也不会自动删除

什么问题呢？

**Comment by cytvictor** [comment]
config.php在安装的时候有没有写入权限？
依你的问题来看，检查config.php内容是否为空，如果是，请重新安装并设置可写权限

**Comment by Johnhacker** [comment]
好的 已解决 谢谢

**Comment by Johnhacker** [comment]
但是有个新问题，点击上传反应很慢，点击按钮，要等待一段时间才有弹出

**Comment by HFO4** [comment]
这和你自身电脑配置有关。可以试下重启浏览器，清理缓存。一般情况下反应还是挺迅速的
