### ISSUE TITLE
禁止商业使用违反GPLv3许可证

### ISSUE THREAD

**Issue by SwimmingTiger** [HFO4/shudong-share#16]
以下内容摘录自《[GNU通用公共许可证第三版非官方简体中文译本](http://www.360doc.com/content/12/1107/11/621500_246348263.shtml)》，虽然不是官方翻译，但是内容基本是准确的：

7．附加条款
----------
…………

尽管本授权在别处有提供，对于您加入到程序中的材料，您可以（如果您由该材料的版权所有者授权的话）用以下条款补充本授权：

a. 拒绝担保责任或以与本授权第15和16小节条款不同的方式限制责任；或者

b. 要求保留特定的合理法律通告，或者该材料中或包含于适当法律通告中的该程序的作者贡献；或者

c. 禁止误传该材料的来源，或者要求该材料的修改版本以合理的方式标志为与原版本不同的版本；或者

d. 限制以宣传为目的的使用该材料作者或授权人的姓名；或者

e. 降低授权级别以在商标法下使用一些商品名称，商标或服务标记；或者

f. 要求任何发布该材料（或其修改版本）的人用对接收者的责任假设合同对授权人和材料作者进行保护，避免任何这样的假设合同直接造成授权人和作者的责任。

**所有其他不许可的附加条款**都被认为是第10节 中的“进一步的约束”。如果您收到的程序或者其部分，**声称自己由本授权管理**，并补充了进一步约束，那么**您可以删除这些约束**。如果一个授权文件包含进一步约束，但是允许再次授权或者在本授权下发布，只要这样的进一步的约束在这样的再次授权或发布中**无法保留下来**，您就可以在覆盖程序中加入该授权文件条款管理下的材料。

10.下游接收者的自动授权
-----------------
…………

您**不可以**对从本授权协议获取或确认的权利的执行**强加任何约束**。比如，您不可以要求授权费用，版税要求或对从本授权获取的权利的执行收取任何费用。您不可以发起诉讼（包括联合诉讼和反诉）声称由于制作、使用、销售、批发或者引进本程序或其任何一部分而侵犯了任何专利权。

-------------
就这两条来看，在[树洞外链发布页面](https://yun.aoaoao.me/buy.php)出现的以下条款构成对用户的“进一步的约束”：

`树洞外链允许你以自由地以非商业化模式使用。不允许你以出售账号、用户组等一切商业形式使用树洞外链。如需要投入商业运营，请购买商业授权。`

因此根据GPLv3，软件作者**不可以**发布这样的条款。如果收到了附带这样条款的软件，用户可以**删除**这样的条款。并且，只要用户发布该软件的修改版，这样的“进一步约束”就完全**无法保留下来**。

-------------
虽然获得商业利益对软件开发者来说非常重要，但是既然选择了 GNU 通用公共许可证，您就有义务遵守它的全部条款，无论您是否愿意这样做。这个许可是**不可修改，不可撤销**的。

最后摘录一段来自GNU通用公共许可证的话做为结束：

12．不要放弃别人的自由
-------------

如果您遇到了与本授权相矛盾的情况（无论是法庭判决，合同或者其他情况），它们不能使您免去本授权的要求。如果您不能同时按照本授权中的义务和其他相关义务来发布覆盖程序，那么您将不能发布它们。比如，如果您接受了要求您向从您这里获取本程序的人收取版税的条款，您唯一能够同时满足本授权和那些条款的方法是**完全不要发布本程序**。

**Comment by MoeGakuen** [comment]
厉害了word哥，直接搬条款

**Comment by SwimmingTiger** [comment]
某虎是自由软件的不狂热支持者，不像理查德·斯托曼那样认为非自由软件就不应该存在。但是某虎对自由软件的“非自由约束”是敏感的。实话说，当看到那句“不允许你以……一切商业形式使用树洞外链”的时候，某虎是挺生气的，因为就某虎目前对法律文本的理解来看，GPL在这里显然被不合理使用了。一个真正的自由软件不能限制用户使用软件的方式，无论用户是自己使用还是让他人付费使用，都完全符合GPLv3和《著作权法》的要求，因为软件的作者已经通过GPLv3向用户授予了无条件的、不可撤销的运行该软件的权力（让他人付费使用由该软件提供的服务显然只是一种运行该软件的行为，而不是分发该软件的行为或者其他行为），这种授权的效力是由《著作权法》的软件许可证相关条款来保障的。

说了这么多，某虎并不是要出售外链服务。某虎只是一种“斯托曼式情节”的爆发而已。而正是这种情节在理查德·斯托曼身上的爆发，才让我们有了GPL和在GPL下发行的无数优秀的自由软件。

树洞外链已经是一个优秀的自由软件项目了。希望它做得更好。

**Comment by ghost** [comment]
# 2333

**Comment by cytvictor** [comment]
![r59uq s6vt oek j c a9s](https://cloud.githubusercontent.com/assets/13085122/21663201/af1d956e-d319-11e6-9193-3cfe768d7af4.jpg)
围观

**Comment by HFO4** [comment]
树洞外链最初版本时使用的不是开源协议，而是安装时声明的一些条款，后来选用GPL协议后未变更协议。感谢你的反馈，我会在后续更新中修改相关条款。

**Comment by SwimmingTiger** [comment]
原来是这样，明白了。
