### ISSUE TITLE
save.php问题

### ISSUE THREAD

**Issue by Benny1923** [HFO4/shudong-share#22]
跟上次一样
只是这次影响是`/data`下的档案
`save.php`不会验证档案是否存在，有资料就会回复`key1`
传送已记录的档名可以拿到不同但有效的`key1`
攻击可列举档名直到删除档案
我觉得这很蠢，应该没什么影响
上次PR时我就没修了
造成比较大的实质影响的地方应该是sql，列举造成的资料库壅塞
另外抱歉最近一直给你开issue
要是不认为这算问题就close吧

**Comment by HFO4** [comment]
的确，这个问题存在好久了，前不久一位用户的数据库就被这样刷了，但要修复的话比较麻烦，所以暂时修了。不过非常感谢你的反馈！
