### ISSUE TITLE
在CPANEL的主机上装了有出错，请问应该怎样解决？

### ISSUE THREAD

**Issue by madlaxcb** [HFO4/shudong-share#3]
首页上面报错：Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/madlaxga/public_html/index.php:1) in /home/madlaxga/public_html/includes/userShell.php on line 3
能上传图片，注册能注册，但登陆无反应，后台可以看到有新注册的用户
请问应该如何解决？是否缺少哪些模块未装么？

PHP PEAR 资源包
已安装   版本  操作
Archive_Tar     1.4.0  
Console_Getopt  1.4.1  
PEAR    1.10.1  
Structures_Graph    1.1.1  
XML_RPC     1.5.5  
XML_Util    1.3.0   

Perl 模块
已安装 ▴   版本  操作
common::sense   3.74  
YAML::Syck  1.29  
XML::Simple     2.22  
XML::SAX::Expat     0.51  
XML::SAX::Base  1.08  
XML::SAX    0.99  
XML::Parser     2.44  
XML::NamespaceSupport   1.11  
URI     1.71  
Types::Serialiser   1.0  
Test::Simple    1.001014  
Test::Pod   1.51  
Test::LeakTrace     0.15  
Template    2.26  
Regexp::Assemble    0.37  
Net::HTTP   6.09  
MIME::Types     2.13  
LWP     6.15  
JSON::XS    3.02  
IO::Stringy     2.111  
GnuPG   0.19  
File::NFSLock   1.27  
Email::Simple   2.210  
Email::MessageID    1.406  
Email::MIME::Encodings  1.315  
Email::MIME::ContentType    1.018  
Email::MIME     1.937  
Email::Date::Format     1.005  
Email::Address  1.908  
Digest::SHA1    2.13  
Digest::MD5     2.55  
DBI     1.636  
Crypt::PasswdMD5    1.40  
Crypt::OpenSSL::Random  0.11  
Crypt::OpenSSL::RSA     0.28  
Class::Std::Utils   0.0.3  
Canary::Stability   2011  
CDB_File    0.98  
AppConfig   1.71

**Comment by HFO4** [comment]
php版本是多少

**Comment by HFO4** [comment]
你好，请下载最新的includes/connect.php文件覆盖试试

**Comment by madlaxcb** [comment]
Apache 版本   2.4.18
PHP 版本  5.6.21
MySQL 版本    5.6.30

下载最新的includes/connect.php文件覆盖后首页没有报错信息了，但登陆还是没反应

**Comment by HFO4** [comment]
能提供下url吗

**Comment by HFO4** [comment]
能提供下url吗

**Comment by madlaxcb** [comment]
刚把NS切到百度，现在解析还没生效ORZ
